# Generated by Django 2.1.2 on 2018-10-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('phone_num', models.CharField(blank=True, max_length=15, unique=True)),
                ('donation', models.BooleanField(default=False)),
            ],
        ),
    ]
