# Generated by Django 2.1.2 on 2018-10-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181025_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
