# Generated by Django 2.0 on 2018-10-21 14:22

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_num', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('last_known_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('last_known_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_safe', models.NullBooleanField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('watching', models.ManyToManyField(blank=True, related_name='_user_watching_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
